### ISSUE TITLE
动态修改响应的编码

### ISSUE THREAD

**Issue by zzgxpyy** [b1ackc4t/Assassin#1]
Assassin>new java 123 get
Assassin>add http://10.37.200.6:8099/javaget.jsp 123  java get
Assassin>show
|ID|URL                                 |pass      |type |method  |reqencode|resencode|status|
|1 |http://10.37.200.6:8099/javaget.jsp |123       |java |get     |base64   |base64   |1     |
Assassin|java >session 1
send payload size: 44 Byte
OK
Assassin|java >back    
OK
Assassin >set 1 resencode raw
OK
Assassin >show
|ID|URL                                 |pass      |type |method  |reqencode|resencode|status|
|1 |http://10.37.200.6:8099/javaget.jsp |123       |java |get     |base64   |raw      |1     |
Assassin >session 1
send payload size: 64 Byte
`send payload size: 64 Byte
javax.crypto.IllegalBlockSizeException: Input length must be multiple of 16 when decrypting with padded cipher
        at java.base/com.sun.crypto.provider.CipherCore.prepareInputBuffer(CipherCore.java:1005)
        at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:848)
        at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
        at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2202)
        at org.b1ackc4t.sender.Crypt.decrypt(Crypt.java:32)
        at org.b1ackc4t.sender.Sender.attack(Sender.java:249)
        at org.b1ackc4t.sender.Sender.print(Sender.java:310)
        at org.b1ackc4t.sender.Sender.testCon(Sender.java:288)
        at org.b1ackc4t.main.Console.doSession(Console.java:336)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.b1ackc4t.util.Cmd.oneCmd(Cmd.java:54)
        at org.b1ackc4t.util.Cmd.cmdLoop(Cmd.java:81)
        at org.b1ackc4t.main.Main.main(Main.java:16)
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.b1ackc4t.util.Cmd.oneCmd(Cmd.java:54)
        at org.b1ackc4t.util.Cmd.cmdLoop(Cmd.java:81)
        at org.b1ackc4t.main.Main.main(Main.java:16)
Caused by: java.lang.NullPointerException
        at org.b1ackc4t.sender.Sender.testCon(Sender.java:289)
        at org.b1ackc4t.main.Console.doSession(Console.java:336)
        ... 7 more
`
看说明是 其中响应的编码方式可以动态修改，不知道我这样修改对不对，不管res修改为什么类型，除了base64 其他的都会报错。

**Comment by b1ackc4t** [comment]
修改了响应的编码方式后需要用reset命令重置一下靶机里的恶意类，在set 1 resencode raw后再执行一下reset 1即可，就能正常session了

**Comment by zzgxpyy** [comment]
Ok .TKS.
